apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: meu-spread
  namespace: meu-spread
spec:
  selector:
    matchLabels:
      app: meu-spread
  template:
    metadata:
      labels:
        app: meu-spread
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - image: nginx:latest
        name: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
