prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    retencion: 3d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "standard"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

additionalPrometheusRulesMap:
  rule-name:
    groups:
    - name: PodInfoResquest
      rules: 
      - alert: PodInfoHighRequestLatency
        expr: http_request_latencies_second{quantile="0.5"} > 3
        for: 5m
        annotations:
          summary: "High request latency on {{ $labels.pod }}"
          description: "{{ $labels.pod }} has a median request latency above 1s (current value: {{ $value }}s)"

grafana:
  sidecar:
    datasources:
      defaultDatasourceEnabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-loki-distributed-query-frontend.monitoring:3100
