apiVersion: apps/v1 
kind: Deployment
metadata:
  name: meuweb
spec:
  selector:
    matchLabels:
      app: meuweb
  replicas: 1
  template:
    metadata:
      labels:
        app: meuweb
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
        operator: Exists
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        app: meuweb
      