apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meu-webserver
  name: meu-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-webserver
  template:
    metadata:
      labels:
        app: meu-webserver
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: app
          ports:
            - containerPort: 80
      initContainers:
        - name: config-webserver
          image: alpine
          command: ["sh", "-c", "echo '<h1>HelloGetup</h1>' > /app/index.html"]
          volumeMounts:
            - mountPath: /app
              name: app
      volumes:
        - name: app
          emptyDir: {}
