apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo
  endpoints:
  - port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
