apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meudeploy
  name: meudeploy
  namespace: segredosdesucesso
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meudeploy
  strategy: {}
  template:
    metadata:
      labels:
         app: meudeploy
    spec:
      containers:
      - name: meudeploy-nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret
          mountPath: "/app"
          readOnly: true
      volumes:
      - name: secret 
        secret:
          secretName: meusegredo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
