apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: userx-role
  namespace: developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: userx-role
subjects:
- kind: ServiceAccount
  name: userx
  namespace: developer