apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: userx-role
  namespace: developer
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["*"]

- apiGroups: ["appssud"]
  resources: ["deployments"]
  verbs: ["*"]


