apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meusiteset
  name: meusiteset
  namespace: backend
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: meusiteset
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: meusiteset
    spec:
      containers:
      - name: meusiteset
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-pv
          mountPath: /data
      volumes:
      - name: data-pv
        persistentVolumeClaim:
          claimName: data-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

