apiVersion: v1
kind: Service
metadata:
  name: service-meusiteset
  namespace: backend
  labels:
    app: meusiteset
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: meusiteset
