apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chaves: secretas
  name: meudeploy-2
  namespace: segredosdesucesso
spec:
  replicas: 1
  selector:
    matchLabels:
      chaves: secretas
  strategy: {}
  template:
    metadata:
      labels:
        chaves: secretas
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: myscret 
          valueFrom: 
            secretKeyRef:
              name: meusegredo
              key: segredo
        - name: myscretfile
          valueFrom: 
            secretKeyRef:
              name: meusegredo
              key: chave-secreta
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30